### ISSUE TITLE
使用OBS推流成功，但是在VLC 播放器里用rtmp 流播放失败

### ISSUE THREAD

**Issue by JackYinpei** [penndev/rtmp-go#5]
大佬好，我clone 你的代码之后在本地编译运行了，然后终端有三个地址 分别是rtmp http播放flv的 和http 播放m3u8 的三个地址 我都试了一下在VLC 里的流播放功能里播放 都放不出来，但是我终止后在runtime 文件夹下生成的*.flv文件 却能在VLC 里播放，我在想如果EDGE浏览器里不能播放是因为不支持flv 格式的播放 但是VLC 里还是不能播放我就不知道为啥了
对了 我使用的是OBS推流屏幕的方式 还请大佬帮忙回复下
提issue 不规范 还请见谅

**Comment by penndev** [comment]
根据知道的信息大概两种可能，一种是topic的地址问题，还有一种可能是现在输出的文件帧第一帧没有过滤为关键帧。详细问题可能还要你提供更多信息。

**Comment by penndev** [comment]
刚测试，如果第一帧不是关键帧在win10下的vlc 3.0.18下播放也是正常的只是开始会有黑频，你测试下如果还是不行加下联系方式一块一块讨论下。

**Comment by JackYinpei** [comment]
我在前段使用flv.js 试了下 根据控制台的提示 发现是跨域问题导致的，我添加了一段代码可以在返回response的时候把跨域问题解决掉。我能提个pull request 吗？人生第一次提交开源代码 哈哈哈哈

**Comment by JackYinpei** [comment]
我想加个feature 后续把可以让推流的画面在浏览器里也能播放，可以吗

**Comment by penndev** [comment]
> 我在前段使用flv.js 试了下 根据控制台的提示 发现是跨域问题导致的，我添加了一段代码可以在返回response的时候把跨域问题解决掉。我能提个pull request 吗？人生第一次提交开源代码 哈哈哈哈

可以的，你想改其他的fork过去随便造...
